'use client';
import {useRef,useState,useEffect} from 'react';
import './member-menu.css';
import { SupportFaq } from './support-faq';
type Request=<T>(path:string,init?:RequestInit)=>Promise<T>;
export type MenuPage='home'|'profile'|'recharge'|'wallet'|'shop'|'lottery'|'support'|'notifications';
export function MemberMenu({name,photo,go}:{name:string;photo?:string|null;go:(page:MenuPage)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const close=()=>{dialog.current?.close();trigger.current?.focus();};
 return <><button ref={trigger} className="menu-toggle" aria-label="Open menu" onClick={()=>dialog.current?.showModal()}><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16"/></svg></button><dialog ref={dialog} className="member-drawer" aria-label="Account menu" onClick={e=>{if(e.target===dialog.current){const rect=dialog.current.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)close();}}} onClose={()=>trigger.current?.focus()}><header><span>GENYX</span><button aria-label="Close menu" onClick={close}>×</button></header><button className="menu-profile" onClick={()=>{go('profile');close();}}><span>{photo?<img src={photo} alt="" referrerPolicy="no-referrer"/>:name.slice(0,1)}</span><div><b>{name}</b><small>View your profile</small></div></button><nav>{([['home','Home'],['recharge','Recharge account'],['wallet','Wallet'],['shop','Shop'],['lottery','Lottery'],['support','Support'],['notifications','Notifications']] as [MenuPage,string][]).map(([id,label])=><button key={id} onClick={()=>{go(id);close();}}>{label}<span aria-hidden="true">›</span></button>)}</nav></dialog></>;
}
type Ticket={id:string;userId:string;subject:string;body:string;reply:string|null;status:string;createdAt:string};
export function SupportPanel({request,admin=false}:{request:Request;admin?:boolean}){
 const [rows,setRows]=useState<Ticket[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const path=admin?'/v1/admin/tickets':'/v1/me/tickets';
 const refresh=()=>request<Ticket[]>(path).then(setRows);
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[]);
 return <section className="member-panel" dir={admin?'rtl':'ltr'}><h2>{admin?'تیکت‌های پشتیبانی':'Support'}</h2>{!admin&&<SupportFaq />}<p>{admin?'مشاهده و پاسخ به درخواست کاربران':'Never send passwords, recovery words or private keys.'}</p>{!admin&&<form onSubmit={async e=>{e.preventDefault();if(busy)return;const form=e.currentTarget,values=new FormData(form);setBusy(true);try{await request(path,{method:'POST',body:JSON.stringify({subject:values.get('subject'),body:values.get('body')})});form.reset();await refresh();setError('Ticket sent.');}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}}><label>Subject<input name="subject" required minLength={3} maxLength={150}/></label><label>Message<textarea name="body" required minLength={5} maxLength={4000}/></label><button disabled={busy}>Send ticket</button></form>}<p role="status">{error}</p><button disabled={busy} onClick={()=>void refresh().catch(e=>setError(e.message))}>{admin?'تازه‌سازی':'Refresh'}</button>{rows.map(t=><article key={t.id}><small>{t.status} · {new Date(t.createdAt).toLocaleString()}</small><h3>{t.subject}</h3>{admin&&<small>User: {t.userId}</small>}<p>{t.body}</p>{t.reply&&<blockquote>{t.reply}</blockquote>}{admin&&<form onSubmit={async e=>{e.preventDefault();if(busy)return;const values=new FormData(e.currentTarget);setBusy(true);try{await request(`/v1/admin/tickets/${t.id}/reply`,{method:'POST',body:JSON.stringify({reply:values.get('reply'),status:values.get('status')})});await refresh();setError('پاسخ ثبت شد.');}catch(e){setError(e instanceof Error?e.message:'خطا');}finally{setBusy(false);}}}><label>پاسخ<textarea name="reply" required maxLength={4000}/></label><select name="status"><option value="ANSWERED">پاسخ داده شد</option><option value="CLOSED">بسته شود</option></select><button disabled={busy}>ارسال پاسخ</button></form>}</article>)}</section>;
}
export function NotificationsPanel({request}:{request:Request}){
 const [rows,setRows]=useState<{id:string;title:string;body:string;readAt:string|null}[]>([]),[error,setError]=useState('');
 useEffect(()=>{let active=true;const load=()=>request<typeof rows>('/v1/me/notifications').then(r=>{if(active)setRows(r);}).catch(e=>{if(active)setError(e.message);});void load();const timer=setInterval(load,30000);return()=>{active=false;clearInterval(timer);};},[]);
 return <section className="member-panel"><h2>Notifications</h2><p role="status">{error}</p>{!rows.length&&<p>No notifications yet.</p>}{rows.map(n=><article key={n.id} className={n.readAt?'':'unread'}><small>{n.readAt?'READ':'NEW'}</small><h3>{n.title}</h3><p>{n.body}</p>{!n.readAt&&<button onClick={async()=>{try{await request(`/v1/me/notifications/${n.id}/read`,{method:'POST',body:'{}'});setRows(old=>old.map(r=>r.id===n.id?{...r,readAt:new Date().toISOString()}:r));}catch(e){setError(e instanceof Error?e.message:'Request failed');}}}>Mark as read</button>}</article>)}</section>;
}
